#!/usr/bin/env node
// Replay harness — turns a written earnout clause into something the ledger can evaluate.
//
// Two jobs, in this order:
//   1. Decide whether the clause is expressible in the signed-terms model at all.
//      A clause that cannot be expressed is the finding, not a failure of the harness.
//   2. For an expressible clause, emit a Daml Script that replays the clause's own
//      historical schedule on the ledger and asserts the payout the parties settled on.
//
// Usage:  node replay/compile.mjs [clause.json ...]     (default: every file in replay/clauses)
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const OUT_DIR = path.join(HERE, '..', 'tests', 'daml', 'Replay');

// --- what the signed-terms model can express -------------------------------
// EarnoutTerms fixes: one metric, a per-period target, a count of periods that
// must be met, and one all-or-nothing tranche. Anything else has no home in the
// contract, and saying so early is the point of this step.
const SUPPORTED = {
  periodBasis: ['per-period'],
  payoutType: ['all-or-nothing'],
  thresholdType: ['count-of-periods-met'],
};

function check(clause) {
  const reasons = [];
  const t = clause.terms ?? {};
  const p = t.payout ?? {};
  if (!SUPPORTED.periodBasis.includes(t.periodBasis))
    reasons.push(`periodBasis "${t.periodBasis}" — the contract evaluates each period against a fixed target; a cumulative or catch-up basis would need the signed terms to carry running state, which they deliberately do not.`);
  if (!SUPPORTED.payoutType.includes(p.type))
    reasons.push(`payout type "${p.type}" — the tranche is all-or-nothing. A sliding or pro-rata payout is a different computation and would have to be signed as such.`);
  if (p.type === 'all-or-nothing' && !SUPPORTED.thresholdType.includes(p.thresholdType ?? 'count-of-periods-met'))
    reasons.push(`threshold type "${p.thresholdType}" — the only threshold the contract counts is how many periods were met.`);
  if (Array.isArray(t.metrics) && t.metrics.length > 1)
    reasons.push(`${t.metrics.length} metrics — one metric per agreement. Two metrics means two agreements, or a metric defined as a formula before it reaches the ledger.`);
  if (t.caps || t.floors)
    reasons.push('caps/floors on the tranche — not expressible; the tranche amount is a single signed figure.');
  const sched = clause.schedule ?? [];
  if (sched.length !== t.periods)
    reasons.push(`schedule has ${sched.length} periods but the terms declare ${t.periods}. The contract requires every period reported, in order, exactly once.`);
  sched.forEach((q) => {
    if (q.dispute) {
      const met = q.metricValue >= t.metricTarget;
      const flagged = !met && q.metricValue + (q.oneOffOutflows ?? 0) >= t.metricTarget;
      if (!flagged)
        reasons.push(`period ${q.period} records a dispute, but the ledger only allows a dispute on a flagged verdict (missed target, and the one-off outflows would have carried it). This clause's dispute happened for a reason the contract does not model.`);
    }
  });
  return reasons;
}

// --- reference evaluation: exactly the model's arithmetic -------------------
function evaluate(clause) {
  const t = clause.terms, target = t.metricTarget;
  const verdicts = clause.schedule.map((q) => {
    const met = q.metricValue >= target;
    const flagged = !met && q.metricValue + (q.oneOffOutflows ?? 0) >= target;
    const resolution = q.dispute ? !!q.dispute.arbiterMet : null;
    return { ...q, met, flagged, effectiveMet: resolution === null ? met : resolution };
  });
  const metCount = verdicts.filter((v) => v.effectiveMet).length;
  const payout = metCount >= t.payout.requiredPeriodsMet ? t.payout.amount : 0;
  return { verdicts, metCount, payout };
}

// --- Daml Script emission --------------------------------------------------
const dec = (n) => (Number.isInteger(n) ? `${n}.0` : `${n}`);
const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

function emit(clause, ev) {
  const t = clause.terms, id = clause.id, deal = clause.deal;
  const L = [];
  L.push(`-- GENERATED by replay/compile.mjs from replay/clauses/${clause._file}. Do not edit by hand.`);
  L.push(`-- ${clause.label}`);
  L.push(`-- Provenance: ${clause.provenance}`);
  L.push(`module Replay.${id} where`, '', 'import Daml.Script', 'import Earnout', '');
  L.push(`replay : Script ()`, `replay = script do`);
  L.push(`  buyer   <- allocatePartyByHint (PartyIdHint "${id}Buyer")`);
  L.push(`  seller  <- allocatePartyByHint (PartyIdHint "${id}Seller")`);
  L.push(`  arbiter <- allocatePartyByHint (PartyIdHint "${id}Arbiter")`);
  L.push(`  bank    <- allocatePartyByHint (PartyIdHint "${id}Bank")`, '');
  L.push(`  let terms = EarnoutTerms with`);
  L.push(`        dealId = "${esc(deal.dealId)}"`);
  L.push(`        metricName = "${esc(deal.metricName)}"`);
  L.push(`        quarterlyTarget = ${dec(t.metricTarget)}`);
  L.push(`        totalQuarters = ${t.periods}`);
  L.push(`        requiredMet = ${t.payout.requiredPeriodsMet}`);
  L.push(`        trancheAmount = ${dec(t.payout.amount)}`, '');
  L.push(`  prop <- submit buyer do`);
  L.push(`    createCmd EarnoutProposal with buyer; seller; arbiter; attestor = bank; terms`);
  L.push(`  agr0 <- submit seller do exerciseCmd prop Accept`, '');
  const finalCids = [];
  ev.verdicts.forEach((q, i) => {
    const n = q.period, prev = `agr${i}`;
    L.push(`  -- period ${n}: reported ${dec(q.metricValue)}${q.oneOffOutflows ? `, one-off outflows ${dec(q.oneOffOutflows)}` : ''} → ${q.met ? 'MET' : q.flagged ? 'MISSED (flagged)' : 'MISSED'}`);
    L.push(`  att${n} <- submit bank do`);
    L.push(`    createCmd MetricAttestation with`);
    L.push(`      dealId = "${esc(deal.dealId)}"; attestor = bank; buyer; quarter = ${n}`);
    L.push(`      metricValue = ${dec(q.metricValue)}; oneOffOutflows = ${dec(q.oneOffOutflows ?? 0)}`);
    L.push(`      basisHash = "${esc(q.basisHash ?? `sha256:replay-${id}-p${n}`)}"`);
    L.push(`  (agr${i + 1}, v${n}) <- submit buyer do`);
    L.push(`    exerciseCmd ${prev} SubmitQuarter with attestationCid = att${n}`);
    if (q.dispute) {
      L.push(`  -- the clause's own dispute: ${esc(q.dispute.reasoning ?? 'resolved by the named arbiter')}`);
      L.push(`  d${n} <- submit seller do exerciseCmd v${n} RaiseDispute`);
      L.push(`  v${n}r <- submit arbiter do`);
      L.push(`    exerciseCmd d${n} Resolve with verdictCid = v${n}; resolvedMet = ${q.dispute.arbiterMet ? 'True' : 'False'}; reasoning = "${esc(q.dispute.reasoning ?? '')}"`);
      finalCids.push(`v${n}r`);
    } else {
      finalCids.push(`v${n}`);
    }
    L.push('');
  });
  L.push(`  -- ${ev.metCount} of ${t.periods} periods met (arbiter resolutions applied); ${t.payout.requiredPeriodsMet} required`);
  L.push(`  outcome <- submit seller do`);
  L.push(`    exerciseCmd agr${ev.verdicts.length} Finalize with verdictCids = [${finalCids.join(', ')}]`, '');
  if (ev.payout > 0) {
    L.push(`  -- the parties settled on ${dec(clause.settled.payout)}; the ledger must reach the same figure`);
    L.push(`  case outcome of`);
    L.push(`    Left _ -> abort "replay diverged: ledger closed the earnout unpaid, the parties settled a payout"`);
    L.push(`    Right obligation -> do`);
    L.push(`      tok <- submit buyer do`);
    L.push(`        createCmd CashToken with issuer = buyer; owner = buyer; amount = ${dec(t.payout.amount)}`);
    L.push(`      (paid, _) <- submit buyer do exerciseCmd obligation Settle with tokenCid = tok`);
    L.push(`      Some settled <- queryContractId seller paid`);
    L.push(`      assertMsg "replay diverged: the tranche did not reach the seller" (settled.owner == seller)`);
    L.push(`      assertMsg "replay diverged: settled amount /= the amount the parties settled on"`);
    L.push(`        (settled.amount == ${dec(clause.settled.payout)})`);
  } else {
    L.push(`  -- the parties settled on nothing; the ledger must close the earnout unpaid`);
    L.push(`  case outcome of`);
    L.push(`    Right _ -> abort "replay diverged: ledger created a settlement obligation, the parties paid nothing"`);
    L.push(`    Left closed -> do`);
    L.push(`      Some c <- queryContractId seller closed`);
    L.push(`      assertMsg "replay diverged: earnout closed for the wrong reason" (c.dealId == "${esc(deal.dealId)}")`);
  }
  L.push('');
  return L.join('\n');
}

// --- main ------------------------------------------------------------------
const args = process.argv.slice(2);
const files = args.length ? args
  : fs.readdirSync(path.join(HERE, 'clauses')).filter((f) => f.endsWith('.json') && f !== 'template.json')
      .map((f) => path.join(HERE, 'clauses', f));

let compiled = 0, rejected = 0, diverged = 0;
for (const file of files) {
  const clause = JSON.parse(fs.readFileSync(file, 'utf8'));
  clause._file = path.basename(file);
  console.log(`\n=== ${clause.id} — ${clause.label}`);
  const reasons = check(clause);
  if (reasons.length) {
    rejected++;
    console.log('  DOES NOT COMPILE. This is a finding about the clause, not a bug:');
    reasons.forEach((r) => console.log(`   - ${r}`));
    continue;
  }
  const ev = evaluate(clause);
  console.log(`  compiles. ${ev.metCount}/${clause.terms.periods} periods met → payout ${ev.payout.toLocaleString('en-US')}`);
  console.log(`  parties settled on ${clause.settled.payout.toLocaleString('en-US')} — ${ev.payout === clause.settled.payout ? 'MATCH (reference arithmetic)' : 'DIVERGES (reference arithmetic)'}`);
  if (ev.payout !== clause.settled.payout) diverged++;
  const out = path.join(OUT_DIR, `${clause.id}.daml`);
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(out, emit(clause, ev));
  compiled++;
  console.log(`  wrote tests/daml/Replay/${clause.id}.daml — run 'replay/run.sh' to execute it on the ledger`);
}
console.log(`\n${compiled} compiled, ${rejected} not expressible, ${diverged} diverging from the settled payout by reference arithmetic.`);
console.log('The reference arithmetic is a pre-check. The ledger run is the answer.');
process.exit(diverged > 0 ? 1 : 0);
